test

diff --git a/.github/workflows/ci-cd-testing.yml b/.github/workflows/ci-cd-testing.yml
--- a/.github/workflows/ci-cd-testing.yml
+++ b/.github/workflows/ci-cd-testing.yml
@@ -28,12 +28,15 @@ jobs:
         run: dotnet format --verify-no-changes
         continue-on-error: true
 
+      - name: Run .NET linting
+        run: dotnet format --check
+        continue-on-error: false
+
       - name: Restore unit test dependencies
         run: |
           cd ./unit_tests
           dotnet restore
 
-          
       - name: Run .NET tests
         id: run_dotnet_tests
         run: |
@@ -62,34 +65,34 @@ jobs:
           coverage report --format=markdown > coverage_summary.md
           coverage report --fail-under=90
 
-      - name: Notify Discord about Test Completion
-        if: always()
-        run: |
-          error_message=""
-          # Check .NET test outcome
-          if [ "${{ steps.run_dotnet_tests.outcome }}" == "failure" ]; then
-            dotnet_errors=$(cat unit_tests/cobertura/*/coverage.cobertura.xml 2>/dev/null || echo "No detailed .NET test errors found.")
-            error_message+="❌ **.NET Tests failed**:\n$dotnet_errors\n"
-          fi
+      # - name: Notify Discord about Test Completion
+      #   if: always()
+      #   run: |
+      #     error_message=""
+      #     # Check .NET test outcome
+      #     if [ "${{ steps.run_dotnet_tests.outcome }}" == "failure" ]; then
+      #       dotnet_errors=$(cat unit_tests/cobertura/*/coverage.cobertura.xml 2>/dev/null || echo "No detailed .NET test errors found.")
+      #       error_message+="❌ **.NET Tests failed**:\n$dotnet_errors\n"
+      #     fi
 
-          # Check Python test outcome
-          if [ "${{ steps.run_python_tests.outcome }}" == "failure" ]; then
-            python_errors=$(cat coverage.xml 2>/dev/null || echo "No detailed Python test errors found.")
-            error_message+="❌ **Python Tests failed**:\n$python_errors\n"
-          fi
+      #     # Check Python test outcome
+      #     if [ "${{ steps.run_python_tests.outcome }}" == "failure" ]; then
+      #       python_errors=$(cat coverage.xml 2>/dev/null || echo "No detailed Python test errors found.")
+      #       error_message+="❌ **Python Tests failed**:\n$python_errors\n"
+      #     fi
 
-          # If no errors, mark tests as successful
-          if [ -z "$error_message" ]; then
-            error_message="✅ **All tests passed successfully** for the branch."
-          fi
+      #     # If no errors, mark tests as successful
+      #     if [ -z "$error_message" ]; then
+      #       error_message="✅ **All tests passed successfully** for the branch."
+      #     fi
 
-          # Extract coverage summary
-          if [ -f coverage_summary.md ]; then
-            coverage_summary=$(cat coverage_summary.md)
-            error_message+="**Coverage Summary:**$coverage_summary"
-          else
-            error_message+="\n**Coverage Summary:** Not available."
-          fi
+      #     # Extract coverage summary
+      #     if [ -f coverage_summary.md ]; then
+      #       coverage_summary=$(cat coverage_summary.md)
+      #       error_message+="**Coverage Summary:**$coverage_summary"
+      #     else
+      #       error_message+="\n**Coverage Summary:** Not available."
+      #     fi
 
-          # Send the message to Discord
-          echo '{'"$error_message"'"}' | jq -Rs '{content: .}' | curl -X POST -H "Content-Type: application/json" -d @- ${{ inputs.DEPLOY_WEBHOOK_URL }}
+      #     # Send the message to Discord
+      #     echo '{'"$error_message"'"}' | jq -Rs '{content: .}' | curl -X POST -H "Content-Type: application/json" -d @- ${{ inputs.DEPLOY_WEBHOOK_URL }}
